{% set version = "1.90.0" %}

package:
  name: libboost-mpi
  version: {{ version }}

source:
  url: https://archives.boost.io/release/{{ version }}/source/boost_{{ version|replace(".", "_") }}.tar.gz
  sha256: 5e93d582aff26868d581a52ae78c7d8edf3f3064742c6e77901a1f18a437eea9
  patches:
    - 5eff1ecc8413b0dc93a1ab047d7fed751e6cb40e.patch  # [not win]
    - 0001-Fix-MSMPI-missing-MPI_CXX_BOOL.patch       # [win]
    - 0002-Fix-MPI-compiler-detection.patch

build:
  number: 0
  run_exports:
    - libboost-mpi

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - libboost-devel {{ version }}.*
    - {{ mpi }}

  run_constrained:
    - libboost {{ version }}.*

test:
  commands:
    # Verify library
    - test ! -f $PREFIX/lib/libboost_mpi.a                                               # [unix]
    - test -f $PREFIX/lib/libboost_mpi.dylib                                             # [osx]
    - test -f $PREFIX/lib/libboost_mpi.so                                                # [linux]
    - if not exist %PREFIX%\\Library\\bin\\boost_mpi.dll exit 1                          # [win]
    - if not exist %PREFIX%\\Library\\lib\\boost_mpi.lib exit 1                          # [win]
    - if exist %PREFIX%\\Library\\lib\\libboost_mpi.lib exit 1                           # [win]

about:
  home: http://www.boost.org/
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - sdebionne
